sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t arijitnath92/dockerreact -f Dockerfile.dev .
    
script:
    - docker run -e CI=true arijitnath92/dockerreact npm run test